### ISSUE TITLE
Caused by: java.lang.RuntimeException: Unable to find a even one function for Template('{}.{}@{}',Hash())

### ISSUE THREAD

**Issue by phact** [virtualdataset/virtdata-java#48]
My binding:

    email: Template("{}.{}@{}", LastNames(), FirstNames(), WeightedStrings('@gmail.com:.5;@hotmail.com:.5'))

Error message:

```
	at javax.script.CompiledScript.eval(CompiledScript.java:106)
	at io.engineblock.script.Scenario.run(Scenario.java:136)
	at io.engineblock.script.Scenario.call(Scenario.java:167)
	at io.engineblock.script.Scenario.call(Scenario.java:44)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unable to find a even one function for Template('{}.{}@{}',Hash())
	at io.virtdata.core.VirtDataComposer.resolveFunctionFlow(VirtDataComposer.java:106)
	at io.virtdata.core.VirtDataLibrary.getDataMapper(VirtDataLibrary.java:39)
	at io.virtdata.core.BindingsTemplate.resolveBindings(BindingsTemplate.java:81)
	at io.virtdata.templates.StringBindingsTemplate.resolve(StringBindingsTemplate.java:24)
	at io.engineblock.activities.stdout.StdoutActivity.initOpSequencer(StdoutActivity.java:127)
	at io.engineblock.activities.stdout.StdoutActivity.initActivity(StdoutActivity.java:82)
	at io.engineblock.core.ActivityExecutor.startActivity(ActivityExecutor.java:93)
```

**Comment by jshook** [comment]
I'll look at this now. (My mornings have started very early lately.)

**Comment by jshook** [comment]
You can hash the input before feeding it to Template. I tested that and found an NPE in an internal method that prevented the example from working. So, that is fixed, and I'm pushing a release this morning for it.

The recipe that works here looks like this:
```
email: Hash(); Template("{}.{}@{}", LastNames(), FirstNames(), WeightedStrings('gmail.com:.5;hotmail.com:.5'));
```

**Comment by jshook** [comment]
This is fixed in master.
